import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { Card, PageHeader } from '../components/UI'

export default function AnalyzeProfile() {
  const navigate = useNavigate()
  const [profile, setProfile] = useState({ role: '', skills: '', experience: '' })
  const update = (event) => setProfile({ ...profile, [event.target.name]: event.target.value })
  const submit = (event) => { event.preventDefault(); navigate('/results') }
  return <><PageHeader eyebrow="Profile workspace" title="Analyze your profile" description="Share a little about your experience to begin a skills analysis."/><div className="form-layout"><Card className="form-card"><h2>Your experience, in your words</h2><p>Use a current role, a target role, or a few notes about the work you do.</p><form onSubmit={submit}><div className="field"><label htmlFor="role">Current or target role</label><input id="role" name="role" value={profile.role} onChange={update} placeholder="e.g. Product designer"/></div><div className="field"><label htmlFor="skills">Skills and tools</label><textarea id="skills" name="skills" value={profile.skills} onChange={update} placeholder="List skills, tools, projects, or responsibilities…"/></div><div className="field"><label htmlFor="experience">Experience context <span style={{color:'#999',fontWeight:400}}>(optional)</span></label><textarea id="experience" name="experience" value={profile.experience} onChange={update} placeholder="A short summary of your background" style={{minHeight:78}}/></div><div className="notice">Analysis results will be available when the project model is connected. This form does not generate predictions.</div><div className="form-actions"><button className="button" type="button" onClick={() => setProfile({ role:'', skills:'', experience:'' })}>Clear form</button><button className="button primary" type="submit">Continue to results <span aria-hidden="true">→</span></button></div></form></Card><Card className="info-panel"><div className="insight-badge"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round"><path d="M12 3v3m0 12v3M3 12h3m12 0h3M5.6 5.6l2.1 2.1m8.6 8.6 2.1 2.1m0-12.8-2.1 2.1m-8.6 8.6-2.1 2.1"/><circle cx="12" cy="12" r="4"/></svg></div><div className="eyebrow" style={{marginTop:15}}>Make a useful start</div><p>A little context goes a long way. You can include the skills you use today or the work you hope to do next.</p><div className="info-list"><div><span className="check-mark">✓</span><span>Include tools and methods you use</span></div><div><span className="check-mark">✓</span><span>Think about responsibilities, too</span></div><div><span className="check-mark">✓</span><span>Keep it in your own words</span></div></div></Card></div></>
}
